name: dartspatcher
description: A simple router dispatcher for HTTP server like expressjs to serve REST api and static files.
version: 0.5.3
homepage: https://github.com/getdbjs/dartspatcher
repository: https://github.com/getdbjs/dartspatcher
issue_tracker: https://github.com/getdbjs/dartspatcher/issues
documentation: https://github.com/getdbjs/dartspatcher

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+3

dev_dependencies:
  test: ^1.15.7
