name: dartspatcher
description: A simple http dispatcher for Dart server.
version: 0.3.0
homepage: https://github.com/getdbjs/dartspatcher
repository: https://github.com/getdbjs/dartspatcher
issue_tracker: https://github.com/getdbjs/dartspatcher/issues
documentation: https://github.com/getdbjs/dartspatcher
author: Davide Bausach <davide.bausach@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+3

dev_dependencies:
  test: ^0.12.0
